/*
Copyright 2011, KISSY UI Library v1.20dev
MIT Licensed
build time: Nov 16 15:05
*/
KISSY.add("htmlparser/Parser",function(k,p,j){function g(f){this.lexer=f}function c(f){this.lexer=new j(f)}g.prototype={nextNode:function(){var f,h,n,m=this.lexer;if(f=m.nextNode())if(f.nodeType==1)if(f.isEndTag())return this.nextNode();else if(n=f.scanner){h=[];f=n.scan(f,m,h)}return f}};c.prototype={elements:function(){return new g(this.lexer)},parse:function(){for(var f=[],h,n=this.elements();h=n.nextNode();)f.push(h);return f}};return c},{requires:["./lexer/Cursor","./lexer/Lexer"]});
KISSY.add("htmlparser/Utils",function(){return{isLetter:function(k){return"a"<=k&&"z">=k||"A"<=k&&"Z">=k},isWhitespace:function(k){return/\s/.test(k)}}});
KISSY.add("htmlparser/dtd",function(k){k=k.merge;var p={isindex:1,fieldset:1},j={input:1,button:1,select:1,textarea:1,label:1},g=k({a:1},j),c=k({iframe:1},g),f={hr:1,ul:1,menu:1,div:1,blockquote:1,noscript:1,table:1,center:1,address:1,dir:1,pre:1,h5:1,dl:1,h4:1,noframes:1,h6:1,ol:1,h1:1,h3:1,h2:1},h={ins:1,del:1,script:1,style:1},n=k({b:1,acronym:1,bdo:1,"var":1,"#":1,abbr:1,code:1,br:1,i:1,cite:1,kbd:1,u:1,strike:1,s:1,tt:1,strong:1,q:1,samp:1,em:1,dfn:1,span:1},h),m=k({sub:1,img:1,object:1,sup:1,
basefont:1,map:1,applet:1,font:1,big:1,small:1},n),q=k({p:1},m);j=k({iframe:1},m,j);m={img:1,noscript:1,br:1,kbd:1,center:1,button:1,basefont:1,h5:1,h4:1,samp:1,h6:1,ol:1,h1:1,h3:1,h2:1,form:1,font:1,"#":1,select:1,menu:1,ins:1,abbr:1,label:1,code:1,table:1,script:1,cite:1,input:1,iframe:1,strong:1,textarea:1,noframes:1,big:1,small:1,span:1,hr:1,sub:1,bdo:1,"var":1,div:1,object:1,sup:1,strike:1,dir:1,map:1,dl:1,applet:1,del:1,isindex:1,fieldset:1,ul:1,b:1,acronym:1,a:1,blockquote:1,i:1,u:1,s:1,tt:1,
address:1,q:1,pre:1,p:1,em:1,dfn:1};var b=k({a:1},j),e={tr:1},a={"#":1},d=k({param:1},m),i=k({form:1},p,c,f,q),l={li:1},o={base:1,link:1,meta:1,title:1},r=k(o,{style:1,script:1}),s={head:1,body:1},t={address:1,blockquote:1,center:1,dir:1,div:1,dl:1,fieldset:1,form:1,h1:1,h2:1,h3:1,h4:1,h5:1,h6:1,hr:1,isindex:1,menu:1,noframes:1,ol:1,p:1,pre:1,table:1,ul:1};return{$nonBodyContent:k({html:1},s,o),$block:t,$blockLimit:{body:1,div:1,td:1,th:1,caption:1,form:1},$inline:b,$body:k({script:1,style:1},t),
$cdata:{script:1,style:1},$empty:{area:1,base:1,br:1,col:1,hr:1,img:1,input:1,link:1,meta:1,param:1},$listItem:{dd:1,dt:1,li:1},$list:{ul:1,ol:1,dl:1},$nonEditable:{applet:1,button:1,embed:1,iframe:1,map:1,object:1,option:1,script:1,textarea:1,param:1},$removeEmpty:{abbr:1,acronym:1,address:1,b:1,bdo:1,big:1,cite:1,code:1,del:1,dfn:1,em:1,font:1,i:1,ins:1,label:1,kbd:1,q:1,s:1,samp:1,small:1,span:1,strike:1,strong:1,sub:1,sup:1,tt:1,u:1,"var":1},$tabIndex:{a:1,area:1,button:1,input:1,object:1,select:1,
textarea:1},$tableContent:{caption:1,col:1,colgroup:1,tbody:1,td:1,tfoot:1,th:1,thead:1,tr:1},html:s,head:r,style:a,body:i,base:{},link:{},meta:{},title:a,col:{},tr:{td:1,th:1},img:{},colgroup:{col:1},noscript:i,td:i,br:{},th:i,center:i,kbd:b,button:k(q,f),basefont:{},h5:b,h4:b,samp:b,h6:b,ol:l,h1:b,h3:b,option:a,h2:b,form:k(p,c,f,q),select:{optgroup:1,option:1},font:b,ins:b,menu:l,abbr:b,label:b,table:{thead:1,col:1,tbody:1,tr:1,colgroup:1,caption:1,tfoot:1},code:b,script:a,tfoot:e,cite:b,li:i,input:{},
iframe:i,strong:b,textarea:a,noframes:i,big:b,small:b,span:b,hr:{},dt:b,sub:b,optgroup:{option:1},param:{},bdo:b,"var":b,div:i,object:d,sup:b,dd:i,strike:b,area:{},dir:l,map:k({area:1,form:1,p:1},p,h,f),applet:d,dl:{dt:1,dd:1},del:b,isindex:{},fieldset:k({legend:1},m),thead:e,ul:l,acronym:b,b:b,a:j,blockquote:i,caption:b,i:b,u:b,tbody:e,s:b,address:k(c,q),tt:b,legend:b,q:b,pre:k(n,g),p:b,em:b,dfn:b}});
KISSY.add("htmlparser/lexer/Cursor",function(){function k(p){this.position=p||0}k.prototype={advance:function(){this.position++},retreat:function(){this.position=Math.max(--this.position,0)}};return k});
KISSY.add("htmlparser/lexer/Index",function(){function k(){this.lineCursors=[]}function p(g,c){for(var f=0;f<g.length;f++)if(g[f].position===c.position)return f;return-1}function j(g,c){for(var f=0;f<g.length;f++)if(g[f].position>c.position)break;return f}k.prototype={add:function(g){p(this.lineCursors,g)==-1&&this.lineCursors.splice(j(this.lineCursors,g),0,g)},remove:function(g){var c=this.lineCursors;g=p(this.lineCursors,g);g!=-1&&c.splice(g,1)},row:function(g){return j(this.lineCursors,g)-1},col:function(g){var c=
j(this.lineCursors,g)-1;return g.position-this.lineCursors[c]}};return k});
KISSY.add("htmlparser/lexer/Lexer",function(k,p,j,g,c,f,h,n,m){function q(b){this.page=new j(b);this.cursor=new p;this.nodeFactory=this}q.prototype={setPosition:function(b){this.cursor.position=b},getPosition:function(){return this.cursor.position},nextNode:function(b){var e,a,d=this.cursor,i=this.page;e=d.position;a=i.getChar(d);switch(a){case -1:b=null;break;case "<":a=i.getChar(d);if(a==-1)b=this.makeString(e,d.position);else if(a=="/"||f.isLetter(a)){i.ungetChar(d);b=this.parseTag(e)}else if("!"==
a){a=i.getChar(d);if(a==-1)b=this.makeString(e,d.position);else if(">"==a)b=this.makeComment(e,d.position);else{i.ungetChar(d);if("-"==a)b=this.parseComment(e,b);else{i.ungetChar(d);b=this.parseTag(e)}}}else{i.ungetChar(d);b=this.parseString(e,b)}break;default:i.ungetChar(d);b=this.parseString(e,b)}return b},makeComment:function(b,e){var a;a=e-b;if(0!=a){if(2>a)return this.makeString(b,e);a=this.nodeFactory.createCommentNode(this.page,b,e)}else a=null;return a},makeString:function(b,e){var a=null;
if(e-b>0)a=this.nodeFactory.createStringNode(this.page,b,e);return a},makeCData:function(b,e){var a=null;if(e-b>0)a=this.nodeFactory.createCDataNode(this.page,b,e);return a},makeTag:function(b,e,a){var d;d=e-b;if(0!=d){if(2>d)return this.makeString(b,e);b=this.nodeFactory.createTagNode(this.page,b,e,a)}else b=null;return b},createTagNode:function(b,e,a,d){return new n(b,e,a,d)},createStringNode:function(b,e,a){return new g(b,e,a)},createCDataNode:function(b,e,a){return new c(b,e,a)},createCommentNode:function(b,
e,a){return new m(b,e,a)},parseTag:function(b){var e,a=[],d=[],i,l=this.page,o=0,r=this.cursor;for(a[0]=r.position;!e;){a[o+1]=r.position;i=l.getChar(r);switch(o){case 0:if(i==-1||">"==i||"<"==i){if("<"==i){l.ungetChar(r);a[o+1]=r.position}e=true}else f.isWhitespace(i)||(o=1);break;case 1:if(-1==i||">"==i||"<"==i){if("<"==i){l.ungetChar(r);a[o+1]=r.getPosition}this.standalone(d,a);e=true}else if(f.isWhitespace(i)){a[6]=a[2];o=6}else if("="==i)o=2;break;case 2:if(-1==i||">"==i){this.standalone(d,a);
e=true}else if("'"==i){o=4;a[4]=a[3]}else if('"'==i){o=5;a[5]=a[3]}else f.isWhitespace(i)||(o=3);break;case 3:if(-1==i||">"==i){this.naked(d,a);e=true}else if(f.isWhitespace(i)){this.naked(d,a);a[0]=a[4];o=0}break;case 4:if(-1==i){this.single_quote(d,a);e=true}else if("'"==i){this.single_quote(d,a);a[0]=a[5]+1;o=0}break;case 5:if(-1==i){this.double_quote(d,a);e=true}else if('"'==i){this.double_quote(d,a);a[0]=a[6]+1;o=0}break;case 6:if(-1==i){this.standalone(d,a);a[0]=a[6];l.ungetChar(r);o=0}else if(!f.isWhitespace(i))if("="==
i){a[2]=a[6];a[3]=a[7];o=2}else{this.standalone(d,a);a[0]=a[6];l.ungetChar(r);o=0}break;default:throw Error("how ** did we get in state "+o);}}return this.makeTag(b,r.position,d)},parseComment:function(b,e){var a,d,i=this.page,l=this.cursor,o;a=false;for(o=0;!a;){d=i.getChar(l);if(-1==d)a=true;else switch(o){case 0:if(">"==d)a=true;if("-"==d)o=1;else return this.parseString(b,e);break;case 1:if("-"==d){d=i.getChar(l);if(-1==d)a=true;else if(">"==d)a=true;else{i.ungetChar(l);o=2}}else return this.parseString(b,
e);break;case 2:if("-"==d)o=3;else if(-1==d)return this.parseString(b,e);break;case 3:o="-"==d?4:2;break;case 4:if(">"==d)a=true;else f.isWhitespace(d)||(o=2);break;default:throw Error("how ** did we get in state "+o);}}return this.makeComment(b,l.position)},parseString:function(b,e){for(var a=0,d,i=this.page,l=this.cursor,o=0;!a;){d=i.getChar(l);if(-1==d)a=1;else if(e&&0==o&&("'"==d||'"'==d))o=d;else if(e&&0!=o&&"\\"==d){d=i.getChar(l);-1!=d&&"\\"!=d&&d!=o&&i.ungetChar(l)}else if(e&&d==o)o=0;else if(e&&
0==o&&d=="/"){d=i.getChar(l);if(-1==d)a=1;else if("/"==d){do d=i.getChar(l);while(-1!=d&&"\n"!=d)}else if("*"==d){do{do d=i.getChar(l);while(-1!=d&&"*"!=d);d=i.getChar(l);d=="*"&&i.ungetChar(l)}while(-1!=d&&"/"!=d)}else i.ungetChar(l)}else if(0==o&&"<"==d){d=i.getChar(l);if(-1==d)a=1;else{if("/"==d||f.isLetter(d)||"!"==d){a=1;i.ungetChar(l)}i.ungetChar(l)}}}return this.makeString(b,l.position)},parseCDATA:function(b){var e,a,d,i,l,o,r=this.cursor,s=this.page;e=r.position;a=0;d=false;i="";for(o=false;!d;){l=
s.getChar(r);switch(a){case 0:switch(l){case -1:d=true;break;case "'":if(b&&!o)if(""==i)i="'";else if("'"==i)i="";break;case '"':if(b&&!o)if(""==i)i='"';else if('"'==i)i="";break;case "\\":if(b)if(""!=i){l=s.getChar(r);if(-1==l)d=true;else l!="\\"&&l!=i&&s.ungetChar(r)}break;case "/":if(b)if(""==i){l=s.getChar(r);if(-1==l)d=true;else if("/"==l)o=true;else if("*"==l){do{do l=s.getChar(r);while(-1!=l&&"*"!=l);l=s.getChar(r);l=="*"&&s.ungetChar(r)}while(-1!=l&&"/"!=l)}else s.ungetChar(r)}break;case "\n":o=
false;break;case "<":if(b){if(""==i)a=1}else a=1}break;case 1:switch(l){case -1:d=true;break;case "/":a=2;break;case "!":l=s.getChar(r);if(-1==l)d=true;else if("-"==l){l=s.getChar(r);if(-1==l)d=true;else a="-"==l?3:0}else a=0;break;default:a=0}break;case 2:o=false;if(-1==l)d=true;else if(f.isLetter(l)){d=true;s.ungetChar(r);s.ungetChar(r);s.ungetChar(r)}else a=0;break;case 3:o=false;if(-1==l)d=true;else if("-"==l){l=s.getChar(r);if(-1==l)d=true;else if("-"==l){l=s.getChar(r);if(-1==l)d=true;else if(">"==
l)a=0;else{s.ungetChar(r);s.ungetChar(r)}}else s.ungetChar(r)}break;default:throw Error("unexpected "+a);}}return this.makeCData(e,r.position)},single_quote:function(b,e){var a=this.page;b.push(new h(a.getText(e[1],e[2]),"=",a.getText(e[4]+1,e[5]),"'"))},double_quote:function(b,e){var a=this.page;b.push(new h(a.getText(e[1],e[2]),"=",a.getText(e[5]+1,e[6]),'"'))},standalone:function(b,e){b.push(new h(this.page.getText(e[1],e[2])))},naked:function(b,e){var a=this.page;b.push(new h(a.getText(e[1],e[2]),
"=",a.getText(e[3],e[4])))}};return q},{requires:["./Cursor","./Page","../nodes/Text","../nodes/CData","../Utils","../nodes/Attribute","../nodes/Tag","../nodes/Comment"]});
KISSY.add("htmlparser/lexer/Page",function(k,p){function j(g){this.source=g;this.lineIndex=new p}j.prototype={getChar:function(g){var c=this.source,f=g.position;if(f>=c.length)return-1;var h=c.charAt(f);g.advance();if("\r"===h){h="\n";f=g.position;c.charAt(f)==="\n"&&g.advance()}"\n"===h&&this.lineIndex.add(g);return h},ungetChar:function(g){var c=this.source;g.retreat();var f=g.position,h=c.charAt(f);if(h==="\n"&&0!=f){h=c.charAt(f-1);"\r"===h&&g.retreat()}},getText:function(g,c){return this.source.slice(g,
c)},row:function(g){return this.lineIndex.row(g)},col:function(g){return this.lineIndex.col(g)}};return j},{requires:["./Index"]});KISSY.add("htmlparser/nodes/Attribute",function(){return function(k,p,j,g){this.nodeType=2;this.name=k;this.assignMent=p;this.value=j;this.quote=g}});
KISSY.add("htmlparser/nodes/CData",function(k,p){function j(){j.superclass.constructor.apply(this,arguments);this.nodeType=4;this.nodeName="#cdata"}k.extend(j,p,{writeHtml:function(g,c){var f=this.toHtml();c.onCData(this)!==false&&g.cdata(f)}});return j},{requires:["./Text"]});
KISSY.add("htmlparser/nodes/Comment",function(k,p){function j(){j.superclass.constructor.apply(this,arguments);this.nodeType=8;this.nodeName="#comment"}k.extend(j,p,{writeHtml:function(g,c){var f=this.toHtml();if(!c||c.onComment(this)!==false)g.comment(f)}});return j},{requires:["./Tag"]});
KISSY.add("htmlparser/nodes/Node",function(k){function p(j,g,c){this.parentNode=null;this.page=j;this.startPosition=g;this.endPosition=c;this.nextSibling=this.previousSibling=this.nodeName=null;if(k.Config.debug)this.toHtmlContent=this.toHtml()}p.prototype={toHtml:function(){if(this.page)return this.page.getText(this.startPosition,this.endPosition)},toString:function(){var j=[];j.push(this.nodeName+"  ["+this.startPosition+":"+this.endPosition+"]\n");j.push(this.toHtml());return j.join("")}};return p});
KISSY.add("htmlparser/nodes/Tag",function(k,p,j,g,c,f,h){function n(e,a,d,i){n.superclass.constructor.apply(this,arguments);this.childNodes=[];this.lastChild=this.firstChild=null;this.attributes=i||[];this.nodeType=1;i=this.attributes;if(i[0]){this.nodeName=i[0].name.toLowerCase();this.tagName=this.nodeName.replace(/\//,"");this.isEmptyXmlTag=!!h.$empty[this.nodeName];if(!this.isEmptyXmlTag)this.isEmptyXmlTag=/\/$/.test(this.nodeName);i.splice(0,1)}if(!this.isEmptyXmlTag){var l=i[i.length-1];if(this.isEmptyXmlTag=
!!(l&&/\/$/.test(l.name)))i.length-=1}this.closed=this.isEmptyXmlTag;this.closedEndPosition=this.closedStartPosition=-1;this.scanner=b[this.nodeName]||j}function m(e){var a=e.childNodes;e.firstChild=a[0];e.lastChild=a[a.length-1];if(a.length>=1){a[0].nextSibling=a[0].nextSibling=null;a[0].parentNode=e}if(a.length>1){for(var d=0;d<a.length-1;d++){a[d].nextSibling=a[d+1];a[d+1].previousSibling=a[d];a[d+1].parentNode=e}a[a.length-1].nextSibling=null}}function q(e,a){for(var d=0;d<e.length;d++)if(e[d].name==
a)return e[d];return null}var b={style:g,script:g,textarea:c};k.extend(n,p,{isEndTag:function(){return/^\//.test(this.nodeName)},appendChild:function(e){this.childNodes.push(e);m(this)},insertBefore:function(e){var a=e.parentNode.childNodes,d=k.indexOf(e,a);a.splice(d,0,this);m(e.parentNode)},removeChild:function(e){var a=e.parentNode.childNodes,d=k.indexOf(e,a);a.splice(d,1);m(e.parentNode)},getAttribute:function(e){return(e=q(this.attributes,e))&&e.value},setAttribute:function(e,a){var d=q(this.attributes,
e);if(d)d.value=a;else this.attributes.push(new f(e,"=",a,'"'))},removeAttribute:function(e){(e=q(this.attributes,e))&&this.attributes.splice(k.indexOf(e,this.attributes),1)},writeHtml:function(e,a){var d=this,i;i=d.tagName;if(a){if(!(i=a.onTagName(i)))return;d.tagName=i;i=a.onTag(d);if(i===false)return;if(i)d=i;if(d.nodeType!==1){d.writeHtml(e,a);return}if(!d.tagName){k.each(d.childNodes,function(s){s.writeHtml(e,a)});return}}e.openTag(d);for(var l=d.attributes,o=0;o<l.length;o++){var r=l[o];i=r.name;
if(a){if(!(i=a.onAttributeName(i)))continue;if(a.onAttribute(r)===false)continue}e.attribute(r,d)}e.openTagClose(d);if(!d.isEmptyXmlTag){k.each(d.childNodes,function(s){s.writeHtml(e,a)});e.closeTag(d)}}});return n},{requires:["./Node","../scanners/TagScanner","../scanners/QuoteCdataScanner","../scanners/TextareaScanner","./Attribute","../dtd"]});
KISSY.add("htmlparser/nodes/Text",function(k,p){function j(){j.superclass.constructor.apply(this,arguments);this.nodeType=3;this.nodeName="#text"}k.extend(j,p,{writeHtml:function(g,c){var f=this.toHtml();if(!c||c.onText(this)!==false)g.text(f)}});return j},{requires:["./Node"]});
KISSY.add("htmlparser/scanners/CdataScanner",function(){return{scan:function(k,p,j,g){j=p.parseCDATA(g);g=p.getPosition();var c=p.nextNode();if(c)if(c.nodeType!=1||!(c.isEndTag()&&c.tagName==k.tagName))p.setPosition(g);k.closed=true;j&&k.appendChild(j);return k}}});KISSY.add("htmlparser/scanners/QuoteCdataScanner",function(k,p){return{scan:function(j,g,c){return p.scan(j,g,c,true)}}},{requires:["./CdataScanner"]});
KISSY.add("htmlparser/scanners/TagScanner",function(k,p){var j={scan:function(g,c,f){var h,n;if(g.isEmptyXmlTag)g.closed=true;else{do{if(h=c.nextNode())if(h.nodeType===1)if(h.isEndTag()&&h.tagName==g.tagName){g.closed=true;h=null}else if(!h.isEndTag()&&!this.canHasNodeAsChild(g,h)){c.setPosition(h.startPosition);h=null}else if(h.isEndTag()){var m=-1;for(n=f.length-1;n>=0;n--){var q=f[n];if(q.tagName===h.tagName){m=n;break}else if(!this.canHasNodeAsChild(q,h)){m=n;break}}if(m!=-1){g.closed=true;f[f.length-
1].appendChild(g);for(n=f.length-1;n>m;n--){g=f[n];h=f[n-1];g.closed=true;h.appendChild(g)}g=f[m];f.length=m;h=null}}else if(n=h.scanner)if(n===j)if(h.isEmptyXmlTag)g.appendChild(h);else{f.push(g);g=h}else{h=n.scan(h,c,f);g.appendChild(h)}else g.appendChild(h);else g.appendChild(h);if(h==null)if(f.length>0){h=f[f.length-1];if(h.nodeType==1)if(h.scanner===j){f.length-=1;g.closed=true;h.appendChild(g);g=h}else h=null;else h=null}}while(h);g.closed=true}return g},canHasNodeAsChild:function(g,c){var f=
c.nodeName;if(c.nodeType==3)f="#";return!!p[g.tagName][f]}};return j},{requires:["../dtd"]});KISSY.add("htmlparser/scanners/TextareaScanner",function(k,p){return{scan:function(j,g,c){return p.scan(j,g,c,false)}}},{requires:["./CdataScanner"]});
KISSY.add("htmlparser/writer/basic",function(k){function p(){this.output=[]}p.prototype={append:function(){for(var j=this.output,g=arguments,c,f=0;f<g.length;f++){c=g[f];if(c.length>1)for(var h=0;h<c.length;h++)j.push(c.charAt(h));else j.push(c)}return this},openTag:function(j){this.append("<",j.tagName)},openTagClose:function(j){j.isEmptyXmlTag&&this.append(" ","/");this.append(">")},closeTag:function(j){this.append("</",j.tagName,">")},attribute:function(j){this.append(" ",j.name,'="',k.escapeHTML(j.value||
j.name),'"')},text:function(j){this.append(j)},cdata:function(j){this.append(j)},comment:function(j){this.append(j)},getHtml:function(){return this.output.join("")}};return p});
KISSY.add("htmlparser/writer/beautify",function(k,p,j){function g(){g.superclass.constructor.apply(this,arguments);this.inPre=0;this.indentChar="\t";this.allowIndent=this.indentLevel=0;this.rules={};for(var c in k.merge(j.$nonBodyContent,j.$block,j.$listItem,j.$tableContent,{select:1}))this.setRules(c,{allowIndent:1,breakBeforeOpen:1,breakAfterOpen:1,breakBeforeClose:1,breakAfterClose:1});this.setRules("option",{breakBeforeOpen:1});this.setRules("optiongroup",{breakBeforeOpen:1});this.setRules("br",
{breakAfterOpen:1});this.setRules("title",{allowIndent:0,breakBeforeClose:0,breakAfterOpen:0});this.setRules("style",{allowIndent:0,breakBeforeOpen:1,breakAfterOpen:1,breakBeforeClose:1,breakAfterClose:1});this.setRules("script",{allowIndent:0,breakBeforeOpen:1,breakAfterOpen:1,breakBeforeClose:1,breakAfterClose:1});this.setRules("pre",{allowIndent:0})}k.extend(g,p,{indentation:function(){this.inPre||this.append(Array(this.indentLevel+1).join(this.indentChar));this.allowIndent=0},lineBreak:function(){var c=
this.output;if(!this.inPre&&c.length){for(var f=c.length-1;f>=0;f--)if(!/[\r\n\t ]/.test(c[f]))break;c.length=f+1;this.append("\n")}this.allowIndent=1},setRules:function(c,f){this.rules[c]||(this.rules[c]={});k.mix(this.rules[c],f)},openTag:function(c){var f=this.rules[c.tagName]||{};if(this.allowIndent)this.indentation();else if(f.breakBeforeOpen){this.lineBreak();this.indentation()}g.superclass.openTag.apply(this,arguments)},openTagClose:function(c){var f=c.tagName,h=this.rules[f]||{};if(c.isEmptyXmlTag)this.append(" />");
else{this.append(">");h.allowIndent&&this.indentLevel++}h.breakAfterOpen&&this.lineBreak();if(f==="pre")this.inPre=1},closeTag:function(c){var f=c.tagName,h=this.rules[f]||{};h.allowIndent&&this.indentLevel--;if(this.allowIndent)this.indentation();else if(h.breakBeforeClose){this.lineBreak();this.indentation()}g.superclass.closeTag.apply(this,arguments);if(f==="pre")this.inPre=0;h.breakAfterClose&&this.lineBreak()},text:function(c){this.allowIndent&&this.indentation();this.inPre||(c=c.replace(/[\t\r\n ]{2,}|[\t\r\n]/g,
" "));this.append(c)},comment:function(c){this.allowIndent&&this.indentation();this.append(c)}});return g},{requires:["./basic","../dtd"]});
KISSY.add("htmlparser/writer/filter",function(k){function p(){this.tagNames=[];this.attributeNames=[];this.tags=[];this.comments=[];this.texts=[];this.cdatas=[];this.attributes=[]}function j(c,f){for(var h=0;h<c.length;h++)k.each(c[h].value,function(n){f=f.replace(n[0],n[1])});return f}function g(c,f,h){for(var n=0;n<c.length;n++)if(c[n].value.apply(null,f)===false)return false;return h}p.prototype={addRules:function(c,f){f=f||10;for(var h in c){var n=this[h],m;a:{for(m=0;m<n.length;m++)if(n[m].priority>
f){m=m;break a}m=n.length}n.splice(m,0,{value:c[h],priority:f})}},onTagName:function(c){return j(this.tagNames,c)},onAttributeName:function(c){return j(this.attributeNames,c)},onText:function(c){return g(this.texts,[c.toHtml(),c],c)},onCData:function(c){return g(this.cdatas,[c.toHtml(),c],c)},onAttribute:function(c,f){return g(this.attributes,[f,c],f)},onComment:function(c){return g(this.comments,[c.toHtml(),c],c)},onNode:function(c){var f=c.nodeType;if(f===1)return this.onTag(c);else if(f===3)return this.onText(c.toHtml(),
c);else if(f===8)return this.onComment(c.toHtml(),c)},onTag:function(c){for(var f=["^",c.tagName,"$"],h=this.tags,n,m=0;m<f.length;m++)for(var q=f[m],b=0;b<h.length;b++){var e=h[b].value;if(e[q]){if((n=e[q](c))===false)return false;if(n&&n!=e)return this.onNode(n);if(!c.name)return c}}return c}};return p});
KISSY.add("htmlparser/writer/minify",function(k,p){function j(h,n){var m=h.nodeName,q=n.name,b=n.value;if(/^on[a-z]+/.test(q))b=c(b).replace(/^javascript:\s*/i,"").replace(/\s*;$/,"");else if(q==="class")b=c(b).replace(/\s+/g," ");else if(/^(?:a|area|link|base)$/.test(m)&&q==="href"||m==="img"&&/^(?:src|longdesc|usemap)$/.test(q)||m==="object"&&/^(?:classid|codebase|data|usemap)$/.test(q)||m==="q"&&q==="cite"||m==="blockquote"&&q==="cite"||(m==="ins"||m==="del")&&q==="cite"||m==="form"&&q==="action"||
m==="input"&&(q==="src"||q==="usemap")||m==="head"&&q==="profile"||m==="script"&&(q==="src"||q==="for")||/^(?:a|area|object|button)$/.test(m)&&q==="tabindex"||m==="input"&&(q==="maxlength"||q==="tabindex")||m==="select"&&(q==="size"||q==="tabindex")||m==="textarea"&&/^(?:rows|cols|tabindex)$/.test(q)||m==="colgroup"&&q==="span"||m==="col"&&q==="span"||(m==="th"||m=="td")&&(q==="rowspan"||q==="colspan"))b=c(b);else if(q==="style")b=c(b).replace(/\s*;\s*$/,"");return b}function g(){g.superclass.constructor.apply(this,
arguments);this.inPre=0}var c=k.trim,f=RegExp("^(?:class|id|style|title|lang|dir|on(?:focus|blur|change|click|dblclick|mouse(?:down|up|over|move|out)|key(?:press|down|up)))$");k.extend(g,p,{comment:function(h){if(/\[if[^\]]+\]/.test(h)){h=h.replace(/^(\[[^\]]+\]>)\s*/,"$1").replace(/\s*(<!\[endif\])$/,"$1");g.superclass.comment.call(this,h)}},openTag:function(h){if(h.tagName=="pre")this.inPre=1;g.superclass.openTag.apply(this,arguments)},closeTag:function(h){if(h.tagName=="pre")this.inPre=0;g.superclass.closeTag.apply(this,
arguments)},cdata:function(h){h=h.replace(/^(?:\s*\/\*\s*<!\[CDATA\[\s*\*\/|\s*\/\/\s*<!\[CDATA\[.*)/,"").replace(/(?:\/\*\s*\]\]>\s*\*\/|\/\/\s*\]\]>)\s*$/,"");g.superclass.cdata.call(this,h)},attribute:function(h,n){var m=h.name,q=h.value||"",b;b=h.name;b=c(h.value)?0:n==="input"&&b==="value"||f.test(b);if(!(b=b)){b=n.nodeName;var e=h.name,a=h.value;a=c(a.toLowerCase());b=b==="script"&&e==="language"&&a==="javascript"||b==="form"&&e==="method"&&a==="get"||b==="input"&&e==="type"&&a==="text"||b===
"script"&&e==="type"&&a==="text/javascript"||b==="style"&&e==="type"&&a==="text/css"||b==="area"&&e==="shape"&&a==="rect"}if(!b)if(/^(?:checked|disabled|selected|readonly)$/i.test(m))this.append(" ",m);else/^[a-zA-Z0-9-._:]+$/.test(q)?this.append(" ",m,"=",k.escapeHTML(j(n,h))):this.append(" ",m,'="',k.escapeHTML(j(n,h)),'"')},text:function(h){this.inPre||this.append(h.replace(/\s+/g," "))}});return g},{requires:["./basic"]});
KISSY.add("htmlparser",function(k,p,j,g,c,f,h){return{Lexer:p,Parser:j,BasicWriter:g,BeautifyWriter:c,MinifyWriter:f,Filter:h}},{requires:["htmlparser/lexer/Lexer","htmlparser/Parser","htmlparser/writer/basic","htmlparser/writer/beautify","htmlparser/writer/minify","htmlparser/writer/filter"]});
